export default {
  articles: [
    {
      // sample data
      id: '0',
      title: '게시글 제목1',
      content: '게시글 본문, Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas dolore facilis veritatis id, nam totam officia minima consequatur sapiente vel repellendus ea sint officiis numquam similique maxime. Quas, vero eveniet!',
      viewCount: 3000,
      likeCount: 256,
      createdAt: '2020-01-01',
      createdBy: '게시자',
      articleHashTags: ['#해쉬태그1', '#해쉬태그2'],
      isLiked: true,
    },
    {
      // sample data
      id: '1',
      title: '게시글 제목2',
      content: '게시글 본문, Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas dolore facilis veritatis id, nam totam officia minima consequatur sapiente vel repellendus ea sint officiis numquam similique maxime. Quas, vero eveniet!',
      viewCount: 3000,
      likeCount: 256,
      createdAt: '2020-01-01',
      createdBy: '게시자',
      articleHashTags: ['#해쉬태그1', '#해쉬태그2'],
      isLiked: true,
    },
    {
      // sample data
      id: '2',
      title: '게시글 제목3',
      content: '게시글 본문, Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas dolore facilis veritatis id, nam totam officia minima consequatur sapiente vel repellendus ea sint officiis numquam similique maxime. Quas, vero eveniet!',
      viewCount: 3000,
      likeCount: 256,
      createdAt: '2020-01-01',
      createdBy: '게시자',
      articleHashTags: ['#해쉬태그1', '#해쉬태그2'],
      isLiked: true,
    },
    {
      'createdAt': '2022-02-25T02:04:13.456629',
      'createdBy': 'name',
      'modifiedAt': '2022-02-25T02:04:13.456629',
      'modifiedBy': 'name',
      'id': 13,
      'title': 'hihi',
      'content': 'good',
      'viewCount': 2,
      'likeCount': 3,
      'account': {
          'id': 4,
          'nickname': 'hi',
          'email': '12345@gmail.com',
          'role': 'USER',
          'createdAt': '2022-02-24T22:06:46.072293',
      },
      'articleComments': [],
      'articleHashTags': [],
    },
  ],
};
